// Converts the Claude Design source assets into web-ready files under public/.
// Run with: npm run assets
import sharp from "sharp";
import { readdir, mkdir, copyFile, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = path.resolve(root, "..", "claude-design-source");
const ds = path.join(src, "_ds", "solodoor-design-system-69e1c42b-639f-4338-9b7d-6e05d3f00474");
const outImg = path.join(root, "public", "images");
const outFonts = path.join(root, "public", "fonts");

// diy-tool-silicone is replaced by diy-tool-blades, which was added by hand (not part of the design export).
const SKIP = new Set(["bg-source", "texture-plaster", "hero-counter", "logo", "diy-tool-silicone"]);
const MAX_WIDTH = { hero: 1920, footer: 1920, diy: 1920, texture: 1600, payments: 1200, google: 600 };

await mkdir(outImg, { recursive: true });
await mkdir(outFonts, { recursive: true });

for (const file of await readdir(path.join(src, "assets"))) {
  const { name, ext } = path.parse(file);
  if (SKIP.has(name) || ext === ".svg") continue;
  const prefix = name.split("-")[0];
  const width = MAX_WIDTH[prefix] ?? 1200;
  let pipeline = sharp(path.join(src, "assets", file));
  // The payments strip ships with a wide transparent margin; trim it so the footer spacing is real.
  if (name === "payments") pipeline = pipeline.trim();
  const info = await pipeline
    .resize({ width, withoutEnlargement: true })
    .webp({ quality: 82 })
    .toFile(path.join(outImg, `${name}.webp`));
  console.log(`${name}.webp ${info.width}x${info.height} ${(info.size / 1024).toFixed(0)}KB`);
}

await copyFile(path.join(src, "assets", "logo.svg"), path.join(outImg, "logo.svg"));
for (const f of await readdir(path.join(ds, "assets", "fonts"))) {
  await copyFile(path.join(ds, "assets", "fonts", f), path.join(outFonts, f));
}

// Icons: magicoon Regular glyphs, lifted from the design-system bundle.
const bundle = await readFile(path.join(ds, "_ds_bundle.js"), "utf8");
const start = bundle.indexOf("const ICON_DATA = {");
const end = bundle.indexOf("Object.assign(__ds_scope, { ICON_DATA });");
const ICON_DATA = new Function(bundle.slice(start, end) + "; return ICON_DATA;")();
const attr = (tag, key) => tag.match(new RegExp(`${key}="([^"]*)"`))?.[1];
const icons = {};
for (const [name, glyph] of Object.entries(ICON_DATA)) {
  if (glyph.viewBox !== "0 0 24 24") throw new Error(`unexpected viewBox on ${name}`);
  const tags = glyph.body.match(/<[a-z]+[^>]*>/g) ?? [];
  icons[name] = tags.map((tag) => {
    if (!tag.startsWith("<path")) throw new Error(`unexpected element in ${name}: ${tag}`);
    const p = { d: attr(tag, "d") };
    const transform = attr(tag, "transform");
    const fillRule = attr(tag, "fill-rule");
    if (transform && transform !== "matrix(1 0 0 1 0 0)") p.transform = transform;
    if (fillRule && fillRule !== "nonzero") p.fillRule = fillRule;
    return p;
  });
}
const ts = `// Generated by scripts/build-assets.mjs from the SOLODOOR design system (magicoon Regular, 24x24).
// Do not edit by hand.
export interface IconPath {
  d: string;
  transform?: string;
  fillRule?: "evenodd";
}

export const ICON_DATA = ${JSON.stringify(icons, null, 2)} as const satisfies Record<string, readonly IconPath[]>;

export type IconName = keyof typeof ICON_DATA;
`;
await writeFile(path.join(root, "src", "components", "solodoor", "icon-data.ts"), ts);
console.log(`icons: ${Object.keys(icons).length}`);
