/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char1495Char1504Char1493Char1514RouteImport } from './routes/חנות'
import { Route as Char1502Char1488Char1502Char1512Char1497Char1501RouteImport } from './routes/מאמרים'
import { Route as Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514RouteImport } from './routes/ציפוי-דלתות'
import { Route as Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501RouteImport } from './routes/ציפוי-מטבחים'
import { Route as Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514RouteImport } from './routes/שאלות-נפוצות'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRouteImport } from './routes/טפט-לפי-סגנון.index'
import { Route as Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRouteImport } from './routes/טפט-לפי-סגנון.$style'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char1495Char1504Char1493Char1514Route =
  Char1495Char1504Char1493Char1514RouteImport.update({
    id: '/חנות',
    path: '/חנות',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char1502Char1488Char1502Char1512Char1497Char1501Route =
  Char1502Char1488Char1502Char1512Char1497Char1501RouteImport.update({
    id: '/מאמרים',
    path: '/מאמרים',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514Route =
  Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514RouteImport.update(
    {
      id: '/ציפוי-דלתות',
      path: '/ציפוי-דלתות',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501Route =
  Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501RouteImport.update(
    {
      id: '/ציפוי-מטבחים',
      path: '/ציפוי-מטבחים',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514Route =
  Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514RouteImport.update(
    {
      id: '/שאלות-נפוצות',
      path: '/שאלות-נפוצות',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRoute =
  Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRouteImport.update(
    {
      id: '/טפט-לפי-סגנון/',
      path: '/טפט-לפי-סגנון/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRoute =
  Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRouteImport.update(
    {
      id: '/טפט-לפי-סגנון/$style',
      path: '/טפט-לפי-סגנון/$style',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/חנות': typeof Char1495Char1504Char1493Char1514Route
  '/מאמרים': typeof Char1502Char1488Char1502Char1512Char1497Char1501Route
  '/ציפוי-דלתות': typeof Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514Route
  '/ציפוי-מטבחים': typeof Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501Route
  '/שאלות-נפוצות': typeof Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514Route
  '/admin/$id': typeof AdminIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/טפט-לפי-סגנון/$style': typeof Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRoute
  '/admin/': typeof AdminIndexRoute
  '/טפט-לפי-סגנון/': typeof Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/accessibility': typeof AccessibilityRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/חנות': typeof Char1495Char1504Char1493Char1514Route
  '/מאמרים': typeof Char1502Char1488Char1502Char1512Char1497Char1501Route
  '/ציפוי-דלתות': typeof Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514Route
  '/ציפוי-מטבחים': typeof Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501Route
  '/שאלות-נפוצות': typeof Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514Route
  '/admin/$id': typeof AdminIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/טפט-לפי-סגנון/$style': typeof Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRoute
  '/admin': typeof AdminIndexRoute
  '/טפט-לפי-סגנון': typeof Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/חנות': typeof Char1495Char1504Char1493Char1514Route
  '/מאמרים': typeof Char1502Char1488Char1502Char1512Char1497Char1501Route
  '/ציפוי-דלתות': typeof Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514Route
  '/ציפוי-מטבחים': typeof Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501Route
  '/שאלות-נפוצות': typeof Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514Route
  '/admin/$id': typeof AdminIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/טפט-לפי-סגנון/$style': typeof Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRoute
  '/admin/': typeof AdminIndexRoute
  '/טפט-לפי-סגנון/': typeof Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/accessibility'
    | '/admin'
    | '/privacy-policy'
    | '/terms'
    | '/חנות'
    | '/מאמרים'
    | '/ציפוי-דלתות'
    | '/ציפוי-מטבחים'
    | '/שאלות-נפוצות'
    | '/admin/$id'
    | '/product/$slug'
    | '/טפט-לפי-סגנון/$style'
    | '/admin/'
    | '/טפט-לפי-סגנון/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/accessibility'
    | '/privacy-policy'
    | '/terms'
    | '/חנות'
    | '/מאמרים'
    | '/ציפוי-דלתות'
    | '/ציפוי-מטבחים'
    | '/שאלות-נפוצות'
    | '/admin/$id'
    | '/product/$slug'
    | '/טפט-לפי-סגנון/$style'
    | '/admin'
    | '/טפט-לפי-סגנון'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/accessibility'
    | '/admin'
    | '/privacy-policy'
    | '/terms'
    | '/חנות'
    | '/מאמרים'
    | '/ציפוי-דלתות'
    | '/ציפוי-מטבחים'
    | '/שאלות-נפוצות'
    | '/admin/$id'
    | '/product/$slug'
    | '/טפט-לפי-סגנון/$style'
    | '/admin/'
    | '/טפט-לפי-סגנון/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  Char1495Char1504Char1493Char1514Route: typeof Char1495Char1504Char1493Char1514Route
  Char1502Char1488Char1502Char1512Char1497Char1501Route: typeof Char1502Char1488Char1502Char1512Char1497Char1501Route
  Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514Route: typeof Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514Route
  Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501Route: typeof Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501Route
  Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514Route: typeof Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514Route
  ProductSlugRoute: typeof ProductSlugRoute
  Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRoute: typeof Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRoute
  Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRoute: typeof Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/חנות': {
      id: '/חנות'
      path: '/חנות'
      fullPath: '/חנות'
      preLoaderRoute: typeof Char1495Char1504Char1493Char1514RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/מאמרים': {
      id: '/מאמרים'
      path: '/מאמרים'
      fullPath: '/מאמרים'
      preLoaderRoute: typeof Char1502Char1488Char1502Char1512Char1497Char1501RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ציפוי-דלתות': {
      id: '/ציפוי-דלתות'
      path: '/ציפוי-דלתות'
      fullPath: '/ציפוי-דלתות'
      preLoaderRoute: typeof Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ציפוי-מטבחים': {
      id: '/ציפוי-מטבחים'
      path: '/ציפוי-מטבחים'
      fullPath: '/ציפוי-מטבחים'
      preLoaderRoute: typeof Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/שאלות-נפוצות': {
      id: '/שאלות-נפוצות'
      path: '/שאלות-נפוצות'
      fullPath: '/שאלות-נפוצות'
      preLoaderRoute: typeof Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/טפט-לפי-סגנון/': {
      id: '/טפט-לפי-סגנון/'
      path: '/טפט-לפי-סגנון'
      fullPath: '/טפט-לפי-סגנון/'
      preLoaderRoute: typeof Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/טפט-לפי-סגנון/$style': {
      id: '/טפט-לפי-סגנון/$style'
      path: '/טפט-לפי-סגנון/$style'
      fullPath: '/טפט-לפי-סגנון/$style'
      preLoaderRoute: typeof Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIdRoute: typeof AdminIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIdRoute: AdminIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  Char1495Char1504Char1493Char1514Route: Char1495Char1504Char1493Char1514Route,
  Char1502Char1488Char1502Char1512Char1497Char1501Route:
    Char1502Char1488Char1502Char1512Char1497Char1501Route,
  Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514Route:
    Char1510Char1497Char1508Char1493Char1497Char1491Char1500Char1514Char1493Char1514Route,
  Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501Route:
    Char1510Char1497Char1508Char1493Char1497Char1502Char1496Char1489Char1495Char1497Char1501Route,
  Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514Route:
    Char1513Char1488Char1500Char1493Char1514Char1504Char1508Char1493Char1510Char1493Char1514Route,
  ProductSlugRoute: ProductSlugRoute,
  Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRoute:
    Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503StyleRoute,
  Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRoute:
    Char1496Char1508Char1496Char1500Char1508Char1497Char1505Char1490Char1504Char1493Char1503IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
